name: Build Flutter APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Fix Gradle
        run: |
          cat > android/gradle/wrapper/gradle-wrapper.properties <<'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.14-bin.zip
          EOF

      - name: Fix Gradle Permission
        run: |
          chmod +x android/gradlew

      - name: Fix Android Gradle Plugin
        run: |
          sed -i 's/com.android.application.*version "[0-9.]*"/com.android.application version "8.12.2"/' android/settings.gradle.kts

      - name: Fix Android Gradle DSL
        run: |
          echo "android.newDsl=false" >> android/gradle.properties

      - name: Check Gradle and AGP
        run: |
          echo "=== Gradle ==="
          cd android
          ./gradlew --version
          echo "=== AGP ==="
          grep -n "com.android.application" settings.gradle.kts || true
          cd ..

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
